# Generated by Django 2.0 on 2018-02-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0006_auto_20180211_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='jobstatus',
            new_name='festfrei',
        ),
    ]
