# Generated by Django 2.0 on 2018-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0009_auto_20180219_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='ProductType',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='position',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
