# Generated by Django 2.0 on 2018-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0010_auto_20180219_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='arbeitszeit',
            new_name='StundenProWoche',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='erfahrung',
            field=models.CharField(choices=[('keine', 'keine'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keine', max_length=10),
        ),
    ]
