# Generated by Django 2.0 on 2018-02-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0011_auto_20180219_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='ZeichenProArtikel',
            new_name='CharPerArticleFree',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='tageProMonat',
            new_name='DaysPerMonthMix',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='erfahrung',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='LohnProAuftrag',
            new_name='FeeFree',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='rating_number',
            new_name='Happiness',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='stundenProTag',
            new_name='HoursPerDayMix',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='StundenProWoche',
            new_name='HoursPerWeekEmp',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='Zeitaufwand',
            new_name='HoursSpentFree',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='medium',
            new_name='Medium',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='MinutenProAudio',
            new_name='MinPerAudioFree',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='MinutenProVideo',
            new_name='MinPerVideoFree',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='position',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='datacollection',
            old_name='salary_number',
            new_name='SalaryPerMonthEmp',
        ),
        migrations.RenameField(
            model_name='medium',
            old_name='festfrei',
            new_name='freeoremployed',
        ),
    ]
