# Generated by Django 2.0 on 2018-02-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0013_auto_20180219_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='Position',
            new_name='JobPosition',
        ),
    ]
